### PR TITLE
300-Create-unit-test-to-package-Mapping-tasks-21-25

### PR DESCRIPTION
**Pull request by otulush**
Dear colleagues please review this pull request

### CODE REVIEW

**Review by MaksymFartushok — APPROVED** [review]
All tests pass successfully, coverage is 100%. Excellent work)

**Review by YuliaPylypenko — APPROVED** [review]
Great job!

**Review by arthurmkrtchian — APPROVED** [review]
I encountered an issue when running tests for "HabitTranslationDtoMapper". They are failed. The problem was resolved by removing the following line from both tests:
`Language language = mock(Language.class);`

and replacing the line when creating the habitTranslation object:
`.language(language)` with `.language(getLanguage())`

> in this case we will use the language object from ModelUtils class

It's possible the issue only arose for me and is related to the specifics of the Java version I'm using. I use Oracle Open JDK version 15.0.2. **The rest of the tests are excellent!**

**Terminal output:**

> org.mockito.exceptions.base.MockitoException: 
> Mockito cannot mock this class: class greencity.entity.Language.
> 
> If you're not sure why you're getting this error, please report to the mailing list.
> 
> Java               : 15
> JVM vendor name    : Oracle Corporation
> JVM vendor version : 15.0.2+7-27
> JVM name           : Java HotSpot(TM) 64-Bit Server VM
> JVM version        : 15.0.2+7-27
> JVM info           : mixed mode, sharing
> OS name            : Linux
> OS version         : 6.2.0-32-generic
> 
> 
> You are seeing this disclaimer because Mockito is configured to create inlined mocks.
> You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.
> 
> Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class greencity.entity.Language]

**Comment by otulush** [comment]
Thanks for the review. There are no issues when using v11. After switching to v15, I encountered the error you provided. So, I modified the code to support both environments.

**Pull request merged**
