### PR TITLE
add ShoppingListItemSpecificationTest.java

### PR DESCRIPTION
**Pull request by MaksymFartushok**
add unit tests for ShoppingListItemSpecification.java, coverage 100%

### CODE REVIEW

**Review by otulush — COMMENTED** [review]
there are compilation errors due to using the next import
import greencity.entity.ShoppingListItem_;
import greencity.entity.localization.ShoppingListItemTranslation_;

**Review by VladyslavSiverskiy — COMMENTED** [review]
@otulush try to follow the instructions in PR #10 , mb it will help you.

**Review by otulush — APPROVED** [review]
All tests passed, 100% coverage

**Review by VladyslavSiverskiy — APPROVED** [review]

**Review by Zhenyettta — APPROVED** [review]
Everything seems correct

**Pull request merged**
