### PR TITLE
added tests for HabitFactController, coverage 100%

### PR DESCRIPTION
**Pull request by YuliaPylypenko**

### CODE REVIEW

**Review by VladyslavSiverskiy — APPROVED** [review]
Everything fine, coverage 100%

**Review by arthurmkrtchian — APPROVED** [review]
Good job, keep it up;)

**Comment by MaksymFartushok** [comment]
Great! excellent work))

**Review by MaksymFartushok — COMMENTED** [review]
It's great!

**Review by MaksymFartushok — COMMENTED** [review]
approve

**Pull request merged**
