### PR TITLE
Issue 300 create unit test to package mapping tasks 6 10

### PR DESCRIPTION
**Pull request by YuliaPylypenko**
Hey, team! Please take a look at the tests responsible for object mapping. If you have any ideas or suggestions for improving the format or appearance of the tests, or if you see **more elegant solution**s, we would greatly appreciate your comments and collaboration in enhancing the quality of our tests.

### CODE REVIEW

**Review by arthurmkrtchian — APPROVED** [review]
The test `convertOriginalComment` fails because two objects with different statuses are being compared. The method `EcoNewsCommentDto `is not fully covered by tests for the scenario when we receive a new comment. Such a comment should be assigned the `CommentStatus.ORIGINAL status.` 
All other tests pass and cover the code 100%. Great job!

**Review by otulush — APPROVED** [review]
All tests passed, 100% coverage. Good job!

**Comment by YuliaPylypenko** [comment]
> The test `convertOriginalComment` fails because two objects with different statuses are being compared. The method `EcoNewsCommentDto `is not fully covered by tests for the scenario when we receive a new comment. Such a comment should be assigned the `CommentStatus.ORIGINAL status.` All other tests pass and cover the code 100%. Great job!

Thank you for pointing that out! We've addressed the issue, and now the test convertOriginalComment accurately covers the scenario for a new comment with the CommentStatus.ORIGINAL status. All tests are passing as expected.

Your feedback was valuable in improving our test coverage. Thanks again for your contribution!

**Review by nklimovych — APPROVED** [review]
Looks great, nice job!

**Pull request merged**
